# Generated by Django 4.2.11 on 2025-09-24 12:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionCalidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Código único del registro', max_length=50, unique=True)),
                ('fecha_registro', models.DateField(help_text='Fecha del registro de clasificación')),
                ('tipo_clasificacion', models.CharField(choices=[('TAMANO', 'Por Tamaño (mm)'), ('GRAMAJE', 'Por Gramaje'), ('CALIDAD', 'Por Calidad'), ('DESCARTE', 'Descarte/Aprovechable'), ('MIXTA', 'Clasificación Mixta')], max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('REGISTRADO', 'Registrado'), ('VERIFICADO', 'Verificado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('registrado_por', models.CharField(help_text='Empleado administrativo que registra', max_length=100)),
                ('cantidad_total_registrada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total registrado en kg', max_digits=12)),
                ('cantidad_stock_original', models.DecimalField(decimal_places=2, help_text='Cantidad original del stock en kg', max_digits=12)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del registro', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('stock_origen', models.ForeignKey(help_text='Stock que se está clasificando', on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='almacenamiento.stock')),
            ],
            options={
                'verbose_name': 'Clasificación de Calidad',
                'verbose_name_plural': 'Clasificaciones de Calidad',
                'ordering': ['-fecha_registro', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TicketAjuste',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_ticket', models.CharField(help_text='Número único del ticket', max_length=50, unique=True)),
                ('tipo_ajuste', models.CharField(choices=[('BAJA', 'Baja por Corrección'), ('ALTA', 'Alta por Corrección')], max_length=10)),
                ('fecha_ajuste', models.DateField(help_text='Fecha del ajuste')),
                ('cantidad_ajuste_kg', models.DecimalField(decimal_places=2, help_text='Cantidad del ajuste en kg', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('motivo', models.TextField(help_text='Motivo detallado del ajuste')),
                ('autorizado_por', models.CharField(help_text='Persona que autoriza el ajuste', max_length=100)),
                ('registrado_por', models.CharField(help_text='Persona que registra el ajuste', max_length=100)),
                ('aplicado', models.BooleanField(default=False, help_text='Indica si el ajuste ya fue aplicado al stock')),
                ('fecha_aplicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('clasificacion_origen', models.ForeignKey(blank=True, help_text='Clasificación que originó este ajuste', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_generados', to='procesamiento.clasificacioncalidad')),
                ('stock_afectado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='almacenamiento.stock')),
            ],
            options={
                'verbose_name': 'Ticket de Ajuste',
                'verbose_name_plural': 'Tickets de Ajuste',
                'ordering': ['-fecha_ajuste', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCalidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_calidad', models.CharField(help_text="Ej: 'Garbanzo 6mm', 'Descarte', etc.", max_length=200)),
                ('valor_especifico', models.CharField(blank=True, help_text="Ej: '6mm', '7mm', 'Primera', etc.", max_length=50, null=True)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='% respecto al total clasificado', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('almacenaje_especifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calidades_almacenadas', to='almacenamiento.almacenaje')),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='procesamiento.clasificacioncalidad')),
                ('ubicacion_especifica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calidades_ubicadas', to='almacenamiento.ubicacion')),
            ],
            options={
                'verbose_name': 'Detalle de Calidad',
                'verbose_name_plural': 'Detalles de Calidad',
                'ordering': ['-porcentaje', 'descripcion_calidad'],
            },
        ),
    ]
