# Generated by Django 5.2.6 on 2025-09-26 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketajuste',
            name='clasificacion_origen',
        ),
        migrations.RemoveField(
            model_name='detallecalidad',
            name='clasificacion',
        ),
        migrations.RemoveField(
            model_name='detallecalidad',
            name='almacenaje_especifico',
        ),
        migrations.RemoveField(
            model_name='detallecalidad',
            name='ubicacion_especifica',
        ),
        migrations.RemoveField(
            model_name='ticketajuste',
            name='stock_afectado',
        ),
        migrations.DeleteModel(
            name='ClasificacionCalidad',
        ),
        migrations.DeleteModel(
            name='DetalleCalidad',
        ),
        migrations.DeleteModel(
            name='TicketAjuste',
        ),
    ]
