# Generated by Django 4.2.11 on 2025-09-24 03:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mercaderias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesoUnitarioReferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('presentacion', models.CharField(choices=[('GRANEL', 'Granel'), ('BOLSA_25', 'Bolsa 25kg'), ('BOLSA_50', 'Bolsa 50kg'), ('BIGBAG_500', 'Big Bag 500kg'), ('BIGBAG_1000', 'Big Bag 1000kg')], max_length=20, unique=True)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'verbose_name': 'Peso Unitario de Referencia',
                'verbose_name_plural': 'Pesos Unitarios de Referencia',
                'ordering': ['presentacion'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PLANTA', 'Planta'), ('ZONA_MIXTA', 'Zona Mixta')], max_length=20)),
                ('encargado_nombre', models.CharField(blank=True, help_text='Nombre del encargado (solo para plantas)', max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReglaAlmacenajePresentacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_almacenaje', models.CharField(choices=[('SILO', 'Silo'), ('SILO_BOLSA', 'Silo Bolsa'), ('GALPON', 'Galpón')], max_length=20)),
                ('tipo_presentacion', models.CharField(choices=[('GRANEL', 'Granel'), ('BOLSA_25', 'Bolsa 25kg'), ('BOLSA_50', 'Bolsa 50kg'), ('BIGBAG_500', 'Big Bag 500kg'), ('BIGBAG_1000', 'Big Bag 1000kg')], max_length=20)),
                ('es_compatible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regla Almacenaje-Presentación',
                'verbose_name_plural': 'Reglas Almacenaje-Presentación',
                'ordering': ['tipo_almacenaje', 'tipo_presentacion'],
                'unique_together': {('tipo_almacenaje', 'tipo_presentacion')},
            },
        ),
        migrations.CreateModel(
            name='FactorConversion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidad_origen', models.CharField(choices=[('KG', 'Kilogramos'), ('TN', 'Toneladas'), ('BOLSAS', 'Bolsas'), ('UNIDADES', 'Unidades')], max_length=20)),
                ('unidad_destino', models.CharField(choices=[('KG', 'Kilogramos'), ('TN', 'Toneladas'), ('BOLSAS', 'Bolsas'), ('UNIDADES', 'Unidades')], max_length=20)),
                ('factor', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
            ],
            options={
                'verbose_name': 'Factor de Conversión',
                'verbose_name_plural': 'Factores de Conversión',
                'ordering': ['unidad_origen', 'unidad_destino'],
                'unique_together': {('unidad_origen', 'unidad_destino')},
            },
        ),
        migrations.CreateModel(
            name='Almacenaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('SILO', 'Silo'), ('SILO_BOLSA', 'Silo Bolsa'), ('GALPON', 'Galpón')], max_length=20)),
                ('codigo', models.CharField(max_length=50)),
                ('capacidad_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('FUMIGACION', 'En Fumigación'), ('MANTENIMIENTO', 'En Mantenimiento'), ('BLOQUEADO', 'Bloqueado')], default='DISPONIBLE', max_length=20)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud_metros', models.DecimalField(blank=True, decimal_places=2, help_text='Longitud en metros (para silo bolsa)', max_digits=8, null=True)),
                ('sentido', models.CharField(blank=True, help_text='Sentido de orientación (para silo bolsa)', max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacenajes', to='almacenamiento.ubicacion')),
            ],
            options={
                'verbose_name': 'Almacenaje',
                'verbose_name_plural': 'Almacenajes',
                'ordering': ['ubicacion__nombre', 'codigo'],
                'unique_together': {('ubicacion', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('almacenaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='almacenamiento.almacenaje')),
                ('mercaderia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='mercaderias.mercaderia')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='almacenamiento.ubicacion')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['ubicacion__nombre', 'almacenaje__codigo', 'mercaderia__grano__nombre'],
                'unique_together': {('ubicacion', 'almacenaje', 'mercaderia')},
            },
        ),
    ]
