# Generated by Django 4.2.11 on 2025-09-24 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('almacenamiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacion',
            name='encargado_nombre',
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='encargado',
            field=models.ForeignKey(blank=True, help_text='Usuario encargado de la ubicación', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
