# Generated by Django 5.2.6 on 2025-09-23 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContacto',
            fields=[
                ('id_tipo_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=200)),
                ('color', models.CharField(default='#007bff', help_text='Color en formato hexadecimal', max_length=7)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Contacto',
                'verbose_name_plural': 'Tipos de Contacto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id_tipo_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=200)),
                ('color', models.CharField(default='#28a745', help_text='Color en formato hexadecimal', max_length=7)),
                ('icono', models.CharField(default='bi-calendar-event', help_text='Clase de icono Bootstrap', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Evento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('empresa', models.CharField(blank=True, max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('telefono_principal', models.CharField(blank=True, max_length=20)),
                ('telefono_secundario', models.CharField(blank=True, max_length=20)),
                ('email_principal', models.EmailField(blank=True, max_length=254)),
                ('email_secundario', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True, max_length=200)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('pais', models.CharField(default='Argentina', max_length=100)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el contacto')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sitio_web', models.URLField(blank=True)),
                ('favorito', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cuenta_relacionada', models.ForeignKey(blank=True, help_text='Cuenta del sistema relacionada con este contacto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.cuenta')),
                ('tipo_contacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.tipocontacto')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('todo_el_dia', models.BooleanField(default=False)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('ubicacion_virtual', models.URLField(blank=True, help_text='Link para reuniones virtuales')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('pospuesto', 'Pospuesto')], default='pendiente', max_length=15)),
                ('recordatorio_activo', models.BooleanField(default=True)),
                ('minutos_recordatorio', models.PositiveIntegerField(default=15, help_text='Minutos antes del evento')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('contactos', models.ManyToManyField(blank=True, help_text='Contactos relacionados con este evento', to='agenda.contacto')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cuenta_relacionada', models.ForeignKey(blank=True, help_text='Cuenta del sistema relacionada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.cuenta')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.tipoevento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('contacto_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.contacto')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cuenta_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.cuenta')),
                ('evento_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.evento')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['fecha_vencimiento', 'prioridad'],
                'indexes': [models.Index(fields=['fecha_vencimiento'], name='agenda_tare_fecha_v_17cb89_idx'), models.Index(fields=['estado'], name='agenda_tare_estado_92a56e_idx'), models.Index(fields=['prioridad'], name='agenda_tare_priorid_6ee4ea_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['nombre', 'apellido'], name='agenda_cont_nombre_b11722_idx'),
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['email_principal'], name='agenda_cont_email_p_a3ea46_idx'),
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['telefono_principal'], name='agenda_cont_telefon_67abc0_idx'),
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['tipo_contacto'], name='agenda_cont_tipo_co_024936_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['fecha_inicio'], name='agenda_even_fecha_i_eb70b0_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['fecha_fin'], name='agenda_even_fecha_f_4b1909_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['estado'], name='agenda_even_estado_fdf40b_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['tipo_evento'], name='agenda_even_tipo_ev_465ceb_idx'),
        ),
    ]
