# Generated by Django 4.2.11 on 2025-09-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='fecha_nacimiento',
        ),
    ]
