# Generated by Django 4.2.11 on 2025-09-23 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0002_remove_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='asignado_a',
            field=models.ForeignKey(blank=True, help_text='Usuario al que se asigna la tarea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='comentarios_asignacion',
            field=models.TextField(blank=True, help_text='Comentarios sobre la asignación o respuesta'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado_asignacion',
            field=models.CharField(choices=[('sin_asignar', 'Sin Asignar'), ('asignada', 'Asignada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='sin_asignar', help_text='Estado de la asignación de la tarea', max_length=15),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_respuesta_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
