# Generated by Django 4.2.11 on 2025-09-23 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0004_asignaciontarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('asignado', 'Asignado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='asignado', max_length=10)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios del usuario sobre la asignación')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='agenda.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Evento',
                'verbose_name_plural': 'Asignaciones de Eventos',
                'ordering': ['-fecha_asignacion'],
                'unique_together': {('evento', 'usuario')},
            },
        ),
    ]
