# Generated by Django 4.2.11 on 2025-09-23 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_comentariotarea'),
    ]

    operations = [
    ]
