# Generated by Django 5.2.6 on 2025-09-22 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.TextField(max_length=150)),
                ('nombre_fantasia', models.TextField(blank=True, max_length=150, null=True)),
                ('numero_documento', models.TextField(max_length=15)),
                ('direccion_cuenta', models.TextField(max_length=200)),
                ('telefono_cuenta', models.TextField(blank=True, max_length=15, null=True)),
                ('celular_cuenta', models.TextField(blank=True, max_length=15, null=True)),
                ('email_cuenta', models.TextField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='localidad',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_localidad', models.TextField(max_length=150)),
                ('cp_localidad', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='situacionIva',
            fields=[
                ('idsituacionIva', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, max_length=150, null=True)),
                ('reducida', models.TextField(blank=True, max_length=10, null=True)),
                ('codigo_afip', models.IntegerField(blank=True, help_text='Código oficial AFIP para la situación de IVA', null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_cuenta',
            fields=[
                ('id_tipo_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_documento',
            fields=[
                ('idtipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=150)),
                ('cod_afip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='contacto_cuenta',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=150)),
                ('cargo', models.TextField(blank=True, max_length=120, null=True)),
                ('email', models.TextField(blank=True, max_length=150, null=True)),
                ('telefono', models.TextField(blank=True, max_length=40, null=True)),
                ('celular', models.TextField(blank=True, max_length=40, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cuenta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='cuentas.cuenta')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='localidad_idlocalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentas.localidad'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='pais_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentas.pais'),
        ),
        migrations.CreateModel(
            name='provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.TextField(max_length=150)),
                ('codigo_provincia', models.TextField(max_length=6)),
                ('pais_idpais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuentas.pais')),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia_id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuentas.provincia'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='provincia_idprovincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentas.provincia'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='situacionIva_idsituacionIva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentas.situacioniva'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='tipo_cuenta_id_tipo_cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentas.tipo_cuenta'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='tipo_documento_idtipo_documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentas.tipo_documento'),
        ),
        migrations.CreateModel(
            name='direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('etiqueta', models.TextField(blank=True, max_length=60, null=True)),
                ('calle', models.TextField(max_length=200)),
                ('numero', models.TextField(blank=True, max_length=20, null=True)),
                ('piso', models.TextField(blank=True, max_length=10, null=True)),
                ('dpto', models.TextField(blank=True, max_length=10, null=True)),
                ('cp', models.TextField(blank=True, max_length=10, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('cuenta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='cuentas.cuenta')),
                ('localidad_idlocalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentas.localidad')),
                ('pais_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentas.pais')),
                ('provincia_idprovincia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentas.provincia')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('cuenta_id',), name='uq_direccion_principal_por_cuenta')],
            },
        ),
        migrations.AddIndex(
            model_name='cuenta',
            index=models.Index(fields=['razon_social'], name='cuentas_cue_razon_s_76b4c7_idx'),
        ),
        migrations.AddIndex(
            model_name='cuenta',
            index=models.Index(fields=['numero_documento'], name='cuentas_cue_numero__0a3cde_idx'),
        ),
        migrations.AddIndex(
            model_name='cuenta',
            index=models.Index(fields=['tipo_cuenta_id_tipo_cuenta'], name='cuentas_cue_tipo_cu_961b6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='cuenta',
            constraint=models.UniqueConstraint(fields=('tipo_documento_idtipo_documento', 'numero_documento'), name='uq_cuenta_doc'),
        ),
    ]
