# Generated by Django 5.2.6 on 2026-03-13 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenamiento', '0002_remove_ubicacion_encargado_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('AUXILIAR', 'Auxiliar'), ('ENCARGADO', 'Encargado'), ('ADMINISTRADOR', 'Administrador'), ('GERENCIA', 'Gerencia')], default='AUXILIAR', help_text='Rol que determina los accesos del usuario.', max_length=15)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('planta', models.ForeignKey(blank=True, help_text='Planta asignada al usuario (requerida para Encargado).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encargados', to='almacenamiento.ubicacion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
