# Generated by Django 4.2.11 on 2025-09-24 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grano',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grano',
                'verbose_name_plural': 'Granos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mercaderia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('PROPIO', 'Propio'), ('TERCERO', 'Tercero')], max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('VENDIDO', 'Vendido'), ('TRANSFERIDO', 'Transferido'), ('RECHAZADO', 'Rechazado')], default='ACTIVO', max_length=20)),
                ('propietario_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('propietario_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('humedad_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('proteina_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cuerpos_extranos_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('granos_danados_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peso_hectolitro', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_analisis', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha límite para almacenamiento', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('grano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercaderias', to='mercaderias.grano')),
            ],
            options={
                'verbose_name': 'Mercadería',
                'verbose_name_plural': 'Mercaderías',
                'ordering': ['-fecha_ingreso', 'grano__nombre'],
            },
        ),
    ]
