# Generated by Django 4.2.11 on 2025-09-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden_presentacion', models.PositiveIntegerField(default=0, help_text='Orden de presentación en listas')),
                ('activo', models.BooleanField(default=True)),
                ('color_hex', models.CharField(blank=True, help_text='Color hexadecimal para visualización (#RRGGBB)', max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Calidad',
                'verbose_name_plural': 'Calidades',
                'ordering': ['orden_presentacion', 'nombre'],
            },
        ),
    ]
