# Generated by Django 4.2.11 on 2025-09-23 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id_camion', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.PositiveIntegerField()),
                ('capacidad_carga', models.DecimalField(decimal_places=2, help_text='Capacidad de carga en toneladas', max_digits=10)),
                ('numero_motor', models.CharField(blank=True, max_length=50)),
                ('numero_chasis', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_viaje', 'En Viaje'), ('mantenimiento', 'En Mantenimiento'), ('fuera_servicio', 'Fuera de Servicio')], default='disponible', max_length=20)),
                ('ubicacion_actual', models.CharField(blank=True, max_length=200)),
                ('kilometraje', models.PositiveIntegerField(default=0)),
                ('fecha_vencimiento_vtv', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento_seguro', models.DateField(blank=True, null=True)),
                ('numero_poliza', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('propietario', models.ForeignKey(blank=True, help_text='Cuenta propietaria del camión (si es tercerizado)', null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentas.cuenta')),
            ],
            options={
                'verbose_name': 'Camión',
                'verbose_name_plural': 'Camiones',
                'ordering': ['patente'],
            },
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id_chofer', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(max_length=200)),
                ('legajo', models.CharField(max_length=20, unique=True)),
                ('fecha_ingreso', models.DateField()),
                ('tipo_licencia', models.CharField(choices=[('A1', 'Licencia A1'), ('A2', 'Licencia A2'), ('A3', 'Licencia A3'), ('B1', 'Licencia B1'), ('B2', 'Licencia B2'), ('C1', 'Licencia C1'), ('C2', 'Licencia C2'), ('D1', 'Licencia D1'), ('D2', 'Licencia D2'), ('D3', 'Licencia D3'), ('E1', 'Licencia E1'), ('E2', 'Licencia E2'), ('E3', 'Licencia E3')], max_length=5)),
                ('numero_licencia', models.CharField(max_length=20)),
                ('fecha_vencimiento_licencia', models.DateField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_viaje', 'En Viaje'), ('descanso', 'En Descanso'), ('vacaciones', 'De Vacaciones'), ('licencia', 'Con Licencia'), ('suspendido', 'Suspendido')], default='disponible', max_length=15)),
                ('contacto_emergencia_nombre', models.CharField(max_length=100)),
                ('contacto_emergencia_telefono', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('camion_asignado', models.ForeignKey(blank=True, help_text='Camión habitualmente asignado a este chofer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transportes.camion')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chofer',
                'verbose_name_plural': 'Choferes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoCamion',
            fields=[
                ('id_tipo_camion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=200)),
                ('capacidad_maxima', models.DecimalField(decimal_places=2, help_text='Capacidad máxima en toneladas', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Camión',
                'verbose_name_plural': 'Tipos de Camión',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.AutoField(primary_key=True, serialize=False)),
                ('numero_viaje', models.CharField(max_length=20, unique=True)),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True)),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tipo_carga', models.CharField(choices=[('carga', 'Carga'), ('descarga', 'Descarga'), ('traslado', 'Traslado'), ('retorno_vacio', 'Retorno Vacío')], max_length=15)),
                ('descripcion_carga', models.TextField(blank=True)),
                ('peso_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='Peso estimado en toneladas', max_digits=10, null=True)),
                ('peso_real', models.DecimalField(blank=True, decimal_places=2, help_text='Peso real medido en balanza', max_digits=10, null=True)),
                ('precio_acordado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('en_curso', 'En Curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('demorado', 'Demorado')], default='planificado', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transportes.camion')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transportes.chofer')),
                ('cliente', models.ForeignKey(help_text='Cliente que solicita el transporte', on_delete=django.db.models.deletion.PROTECT, to='cuentas.cuenta')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='TicketBalanza',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('numero_ticket', models.CharField(max_length=20, unique=True)),
                ('fecha_pesaje', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_pesaje', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('control', 'Control')], max_length=10)),
                ('peso_bruto', models.DecimalField(decimal_places=2, help_text='Peso bruto en kilogramos', max_digits=10)),
                ('peso_tara', models.DecimalField(decimal_places=2, default=0, help_text='Peso de la tara en kilogramos', max_digits=10)),
                ('peso_neto', models.DecimalField(decimal_places=2, help_text='Peso neto en kilogramos', max_digits=10)),
                ('producto', models.CharField(max_length=100)),
                ('destino_carga', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('balanza_operador', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transportes.camion')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transportes.chofer')),
                ('cliente_carga', models.ForeignKey(help_text='Cliente de la carga', on_delete=django.db.models.deletion.PROTECT, to='cuentas.cuenta')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(blank=True, help_text='Viaje al que corresponde este pesaje', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transportes.viaje')),
            ],
            options={
                'verbose_name': 'Ticket de Balanza',
                'verbose_name_plural': 'Tickets de Balanza',
                'ordering': ['-fecha_pesaje'],
            },
        ),
        migrations.AddField(
            model_name='camion',
            name='tipo_camion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transportes.tipocamion'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['numero_viaje'], name='transportes_numero__7665e9_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['estado'], name='transportes_estado_a51c98_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['fecha_programada'], name='transportes_fecha_p_727d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['camion'], name='transportes_camion__a4e1f9_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['chofer'], name='transportes_chofer__344048_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketbalanza',
            index=models.Index(fields=['numero_ticket'], name='transportes_numero__fa7e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketbalanza',
            index=models.Index(fields=['fecha_pesaje'], name='transportes_fecha_p_4a76b7_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketbalanza',
            index=models.Index(fields=['camion'], name='transportes_camion__b78ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketbalanza',
            index=models.Index(fields=['tipo_pesaje'], name='transportes_tipo_pe_3a99a4_idx'),
        ),
        migrations.AddIndex(
            model_name='chofer',
            index=models.Index(fields=['dni'], name='transportes_dni_794803_idx'),
        ),
        migrations.AddIndex(
            model_name='chofer',
            index=models.Index(fields=['legajo'], name='transportes_legajo_1c1a86_idx'),
        ),
        migrations.AddIndex(
            model_name='chofer',
            index=models.Index(fields=['estado'], name='transportes_estado_bf7e70_idx'),
        ),
        migrations.AddIndex(
            model_name='camion',
            index=models.Index(fields=['patente'], name='transportes_patente_fbabcb_idx'),
        ),
        migrations.AddIndex(
            model_name='camion',
            index=models.Index(fields=['estado'], name='transportes_estado_74feb7_idx'),
        ),
        migrations.AddIndex(
            model_name='camion',
            index=models.Index(fields=['tipo_camion'], name='transportes_tipo_ca_b74ba0_idx'),
        ),
    ]
