# Generated by Django 4.2.11 on 2025-09-23 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
        ('transportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='camion',
            name='transportes_estado_74feb7_idx',
        ),
        migrations.RemoveIndex(
            model_name='camion',
            name='transportes_tipo_ca_b74ba0_idx',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='año',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='kilometraje',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='numero_motor',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='tipo_camion',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='ubicacion_actual',
        ),
        migrations.AddField(
            model_name='camion',
            name='acoplado_1',
            field=models.CharField(blank=True, help_text='Patente del primer acoplado', max_length=10),
        ),
        migrations.AddField(
            model_name='camion',
            name='acoplado_2',
            field=models.CharField(blank=True, help_text='Patente del segundo acoplado', max_length=10),
        ),
        migrations.AddField(
            model_name='camion',
            name='cuenta_asociada',
            field=models.ForeignKey(default=1, help_text='Cuenta/empresa propietaria del camión', on_delete=django.db.models.deletion.PROTECT, to='cuentas.cuenta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camion',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones adicionales'),
        ),
        migrations.AddField(
            model_name='camion',
            name='tara',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tara del camión en toneladas', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='camion',
            name='capacidad_carga',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capacidad de carga en toneladas', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='camion',
            name='numero_chasis',
            field=models.CharField(blank=True, help_text='Número de chasis', max_length=50),
        ),
        migrations.AlterField(
            model_name='camion',
            name='patente',
            field=models.CharField(help_text='Patente del camión', max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='camion',
            index=models.Index(fields=['cuenta_asociada'], name='transportes_cuenta__621734_idx'),
        ),
    ]
