# Generated by Django 4.2.11 on 2025-09-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0002_remove_camion_transportes_estado_74feb7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camion',
            name='numero_chasis',
        ),
    ]
