# Generated by Django 4.2.11 on 2025-09-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0003_remove_camion_numero_chasis'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chofer',
            name='transportes_dni_794803_idx',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='dni',
        ),
        migrations.AddField(
            model_name='chofer',
            name='cuit',
            field=models.CharField(default=1, help_text='CUIT en formato XX-XXXXXXXX-X', max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='chofer',
            index=models.Index(fields=['cuit'], name='transportes_cuit_1e62ca_idx'),
        ),
    ]
