# Generated by Django 4.2.11 on 2025-09-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0004_cambiar_dni_por_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='fecha_vencimiento_licencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='numero_licencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='tipo_licencia',
            field=models.CharField(blank=True, choices=[('A1', 'Licencia A1'), ('A2', 'Licencia A2'), ('A3', 'Licencia A3'), ('B1', 'Licencia B1'), ('B2', 'Licencia B2'), ('C1', 'Licencia C1'), ('C2', 'Licencia C2'), ('D1', 'Licencia D1'), ('D2', 'Licencia D2'), ('D3', 'Licencia D3'), ('E1', 'Licencia E1'), ('E2', 'Licencia E2'), ('E3', 'Licencia E3')], max_length=5, null=True),
        ),
    ]
