# Generated by Django 4.2.11 on 2025-09-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0005_hacer_licencias_opcionales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='direccion',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
