# Generated by Django 4.2.11 on 2025-09-29 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
        ('transportes', '0007_hacer_telefono_direccion_opcionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='cuenta_asociada',
            field=models.ForeignKey(default=1, help_text='Cuenta/empresa a la que pertenece el chofer', on_delete=django.db.models.deletion.PROTECT, to='cuentas.cuenta'),
            preserve_default=False,
        ),
    ]
