# Generated by Django 4.2.11 on 2025-09-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0008_chofer_cuenta_asociada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='contacto_emergencia_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='estado',
            field=models.CharField(blank=True, choices=[('disponible', 'Disponible'), ('en_viaje', 'En Viaje'), ('descanso', 'En Descanso'), ('vacaciones', 'De Vacaciones'), ('licencia', 'Con Licencia'), ('suspendido', 'Suspendido')], default='disponible', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='legajo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
