# Generated by Django 5.2.6 on 2025-09-26 11:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenamiento', '0002_remove_ubicacion_encargado_nombre_and_more'),
        ('cuentas', '0001_initial'),
        ('mercaderias', '0003_clasificacioncalidad_ticketajuste_detallecalidad'),
        ('transportes', '0007_hacer_telefono_direccion_opcionales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#6c757d', help_text='Color hexadecimal', max_length=7)),
                ('es_inicial', models.BooleanField(default=False)),
                ('es_final', models.BooleanField(default=False)),
                ('permite_edicion', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado de Ticket',
                'verbose_name_plural': 'Estados de Tickets',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('requiere_origen', models.BooleanField(default=False, help_text='Si requiere cuenta de origen')),
                ('requiere_destinatario', models.BooleanField(default=False, help_text='Si requiere cuenta destinatario')),
            ],
            options={
                'verbose_name': 'Tipo de Movimiento',
                'verbose_name_plural': 'Tipos de Movimientos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='DetalleMercaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_kg', models.DecimalField(decimal_places=2, help_text='Cantidad en kilogramos', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('analisis_realizado', models.BooleanField(default=False)),
                ('fecha_analisis', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('analizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis_realizados', to=settings.AUTH_USER_MODEL)),
                ('calidad_clasificacion', models.ForeignKey(blank=True, help_text='Clasificación de calidad (después del análisis)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mercaderias.clasificacioncalidad')),
                ('mercaderia', models.ForeignKey(help_text='Tipo de mercadería', on_delete=django.db.models.deletion.PROTECT, to='mercaderias.mercaderia')),
                ('ubicacion_almacenaje', models.ForeignKey(blank=True, help_text='Ubicación donde se almacena', null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacenamiento.almacenaje')),
            ],
            options={
                'verbose_name': 'Detalle de Mercadería',
                'verbose_name_plural': 'Detalles de Mercaderías',
            },
        ),
        migrations.CreateModel(
            name='AnalisisMercaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_analisis', models.DateTimeField(default=django.utils.timezone.now)),
                ('humedad', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de humedad', max_digits=5, null=True)),
                ('proteina', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de proteína', max_digits=5, null=True)),
                ('grasa', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de grasa', max_digits=5, null=True)),
                ('parametros_adicionales', models.JSONField(blank=True, default=dict, help_text='Otros parámetros de análisis en formato JSON')),
                ('observaciones_analisis', models.TextField(blank=True)),
                ('aprobado', models.BooleanField(default=True, help_text='Si la mercadería cumple con los estándares')),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analisis_realizados_detalle', to=settings.AUTH_USER_MODEL)),
                ('detalle_mercaderia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='tickets.detallemercaderia')),
            ],
            options={
                'verbose_name': 'Análisis de Mercadería',
                'verbose_name_plural': 'Análisis de Mercaderías',
                'ordering': ['-fecha_analisis'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(editable=False, max_length=20, unique=True)),
                ('patente_camion', models.CharField(help_text='Patente del camión (ej: ABC123DE o ABC123)', max_length=20, validators=[django.core.validators.RegexValidator(message='Formato de patente inválido', regex='^[A-Z]{2,3}[\\d]{3}[A-Z]{2,3}$|^[A-Z]{3}[\\d]{3}$')])),
                ('peso_bruto', models.DecimalField(blank=True, decimal_places=2, help_text='Peso bruto del camión en kg', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('peso_tara', models.DecimalField(blank=True, decimal_places=2, help_text='Peso tara (camión vacío) en kg', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('peso_neto', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Peso neto (bruto - tara) en kg', max_digits=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_llegada', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de llegada del camión')),
                ('fecha_salida', models.DateTimeField(blank=True, help_text='Fecha y hora de salida del camión', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales del ticket')),
                ('chofer', models.ForeignKey(blank=True, help_text='Chofer asignado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transportes.chofer')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_creados', to=settings.AUTH_USER_MODEL)),
                ('cuenta_transporte', models.ForeignKey(blank=True, help_text='Empresa de transporte (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_transporte', to='cuentas.cuenta')),
                ('destinatario', models.ForeignKey(blank=True, help_text='Cuenta destinatario (para envíos)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_destinatario', to='cuentas.cuenta')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.estadoticket')),
                ('origen', models.ForeignKey(blank=True, help_text='Cuenta de origen (para recepciones)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_origen', to='cuentas.cuenta')),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.tipomovimiento')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='detallemercaderia',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_mercaderias', to='tickets.ticket'),
        ),
        migrations.CreateModel(
            name='ComentarioTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-fecha_comentario'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='tickets/archivos/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='detallemercaderia',
            unique_together={('ticket', 'mercaderia')},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['numero_ticket'], name='tickets_tic_numero__84ef8e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['patente_camion'], name='tickets_tic_patente_21d2b7_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tipo_movimiento', 'fecha_creacion'], name='tickets_tic_tipo_mo_e93cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='tickets_tic_estado__7ad690_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['creado_por', 'fecha_creacion'], name='tickets_tic_creado__5bf212_idx'),
        ),
    ]
