# Generated by Django 5.2.6 on 2026-03-13 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenamiento', '0002_remove_ubicacion_encargado_nombre_and_more'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='planta',
            field=models.ForeignKey(blank=True, help_text='Planta donde se registra el pesaje', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='almacenamiento.ubicacion'),
        ),
    ]
