# Generated by Django 5.2.6 on 2026-03-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_add_planta_to_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='patente_acoplado_1',
            field=models.CharField(blank=True, default='', help_text='Patente del primer acoplado/semirremolque', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='patente_acoplado_2',
            field=models.CharField(blank=True, default='', help_text='Patente del segundo acoplado', max_length=20),
        ),
    ]
